"""catching the rest

Revision ID: 7baa86f3a88d
Revises: 9fc8f2044090
Create Date: 2018-03-20 16:49:33.002659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7baa86f3a88d'
down_revision = '9fc8f2044090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_lpr_rank_rank'), 'lpr_rank', ['rank'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lpr_rank_rank'), table_name='lpr_rank')
    # ### end Alembic commands ###
