"""start over

Revision ID: 9d8465c93c85
Revises: 
Create Date: 2018-02-19 16:19:52.639768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d8465c93c85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter_key', sa.String(length=16), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directions_timestamp'), 'directions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_directions_voter_key'), 'directions', ['voter_key'], unique=False)
    op.create_table('fptp_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter_key', sa.String(length=16), nullable=True),
    sa.Column('candid', sa.String(length=40), nullable=True),
    sa.Column('riding', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.String(length=10), nullable=True),
    sa.Column('election', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fptp_vote_candid'), 'fptp_vote', ['candid'], unique=False)
    op.create_index(op.f('ix_fptp_vote_election'), 'fptp_vote', ['election'], unique=False)
    op.create_index(op.f('ix_fptp_vote_riding'), 'fptp_vote', ['riding'], unique=False)
    op.create_index(op.f('ix_fptp_vote_timestamp'), 'fptp_vote', ['timestamp'], unique=False)
    op.create_index(op.f('ix_fptp_vote_voter_key'), 'fptp_vote', ['voter_key'], unique=False)
    op.create_table('lprvote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter_key', sa.String(length=16), nullable=True),
    sa.Column('riding', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('election', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lprvote_district'), 'lprvote', ['district'], unique=False)
    op.create_index(op.f('ix_lprvote_election'), 'lprvote', ['election'], unique=False)
    op.create_index(op.f('ix_lprvote_riding'), 'lprvote', ['riding'], unique=False)
    op.create_index(op.f('ix_lprvote_timestamp'), 'lprvote', ['timestamp'], unique=False)
    op.create_index(op.f('ix_lprvote_voter_key'), 'lprvote', ['voter_key'], unique=False)
    op.create_table('mmp_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter_key', sa.String(length=16), nullable=True),
    sa.Column('candid', sa.String(length=40), nullable=True),
    sa.Column('riding', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('party', sa.String(length=20), nullable=True),
    sa.Column('election', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mmp_vote_candid'), 'mmp_vote', ['candid'], unique=False)
    op.create_index(op.f('ix_mmp_vote_election'), 'mmp_vote', ['election'], unique=False)
    op.create_index(op.f('ix_mmp_vote_party'), 'mmp_vote', ['party'], unique=False)
    op.create_index(op.f('ix_mmp_vote_riding'), 'mmp_vote', ['riding'], unique=False)
    op.create_index(op.f('ix_mmp_vote_timestamp'), 'mmp_vote', ['timestamp'], unique=False)
    op.create_index(op.f('ix_mmp_vote_voter_key'), 'mmp_vote', ['voter_key'], unique=False)
    op.create_table('lpr_rank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candid', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['lprvote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lpr_rank_candid'), 'lpr_rank', ['candid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lpr_rank_candid'), table_name='lpr_rank')
    op.drop_table('lpr_rank')
    op.drop_index(op.f('ix_mmp_vote_voter_key'), table_name='mmp_vote')
    op.drop_index(op.f('ix_mmp_vote_timestamp'), table_name='mmp_vote')
    op.drop_index(op.f('ix_mmp_vote_riding'), table_name='mmp_vote')
    op.drop_index(op.f('ix_mmp_vote_party'), table_name='mmp_vote')
    op.drop_index(op.f('ix_mmp_vote_election'), table_name='mmp_vote')
    op.drop_index(op.f('ix_mmp_vote_candid'), table_name='mmp_vote')
    op.drop_table('mmp_vote')
    op.drop_index(op.f('ix_lprvote_voter_key'), table_name='lprvote')
    op.drop_index(op.f('ix_lprvote_timestamp'), table_name='lprvote')
    op.drop_index(op.f('ix_lprvote_riding'), table_name='lprvote')
    op.drop_index(op.f('ix_lprvote_election'), table_name='lprvote')
    op.drop_index(op.f('ix_lprvote_district'), table_name='lprvote')
    op.drop_table('lprvote')
    op.drop_index(op.f('ix_fptp_vote_voter_key'), table_name='fptp_vote')
    op.drop_index(op.f('ix_fptp_vote_timestamp'), table_name='fptp_vote')
    op.drop_index(op.f('ix_fptp_vote_riding'), table_name='fptp_vote')
    op.drop_index(op.f('ix_fptp_vote_election'), table_name='fptp_vote')
    op.drop_index(op.f('ix_fptp_vote_candid'), table_name='fptp_vote')
    op.drop_table('fptp_vote')
    op.drop_index(op.f('ix_directions_voter_key'), table_name='directions')
    op.drop_index(op.f('ix_directions_timestamp'), table_name='directions')
    op.drop_table('directions')
    # ### end Alembic commands ###
