"""rank LPR ballot

Revision ID: 9fc8f2044090
Revises: 9d8465c93c85
Create Date: 2018-02-25 16:13:45.947036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc8f2044090'
down_revision = '9d8465c93c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lpr_rank', sa.Column('rank', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_lpr_rank_rank'), 'lpr_rank', ['rank'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lpr_rank_rank'), table_name='lpr_rank')
    op.drop_column('lpr_rank', 'rank')
    # ### end Alembic commands ###
